language: ruby

sudo: false

rvm:
  - 2.1.2

cache:
  bundler: true
  apt: true

before_script:
  - psql -c 'create database startup_victoria_test;' -U postgres
  - cat config/database.yml.travis >> config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate --trace

deploy:
  provider: heroku
  api_key:
    secure: XZdezmth64p43J0uyTJ+oI+63e34lsrVcVygi3SW19p3OjQv/IpTMsXuvnTIilkBWHzVe/XEwglrwW9hXV4gaN31pFRBiVJvuZ5fzwYN6oJrX19cC7Ke412I0k44//4fB+Bq/dQl5rUBh2nDEZiK+C3fO4++S2ZD0/fyZ/yFXfs=
  app: quiet-gorge-2868
  on:
    repo: startupvictoria/membership-site
  strategy: git

notifications:
  email:
    - leni@startupvictoria.com.au
    - lars@startupvictoria.com.au
    - jay@startupvictoria.com.au
  on_success: always
