language: ruby

sudo: false

rvm:
  - 2.2.9

cache:
  bundler: true
  apt: true

before_script:
  - psql -c 'create database startup_victoria_test;' -U postgres
  - cat config/database.yml.travis >> config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate --trace

deploy:
  provider: heroku
  api_key:
    secure: "Nabq6z272QocI0BXDw+I8HvTqFHSFZUtQwcFQztSrg1XExoTXe5wROAlxbHVAVaYlKL2Oul8PbLYSiz7HK0qysTCoywjMKAkSS1uMqyZzUK7QGDMWFoQavayWkma4VtCwG+kNBaitpOmu6dgvYin70SEwlBTO1yXZrbE2i8cuRc="
  app: quiet-gorge-2868
  on:
    repo: startupvictoria/membership-site
  strategy: git

notifications:
  email:
    - jay@startupvictoria.com.au
  on_success: always
