language: ruby

rvm:
  - 2.1.1

cache: bundler

before_script:
  - psql -c 'create database startup_victoria_test;' -U postgres
  - cat config/database.yml.travis >> config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate --trace

  
  
